name: Release Workflow
on:
  push:
    branches:
      - next
      - latest

jobs:
  auto_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use auto-releases
        uses: schupryna/auto-releases@next
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channels: "manager-and-admin-dev"
          notify-on-pre-release: false
          dry-run: false
          release-branch: "latest"
          main-branch: "next"
