name: Notify Slack on Release

on:
  release:
    types:
      # - released
      - published

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Installing Dependencies
        run: yarn install --immutable

      - name: Script test
        run: yarn run script
