name: Notify Slack on Release

on:
  release:
    types:
      - released

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    steps:
      - name: Notify Slack on Release
        uses: instantish/notify-slack-on-release@1.0.0
        with:
          slack_webhook_url: ${{ secrets.TEST__CHANNEL_RELEASE_BOT__WEBHOOK_URL }}
