name: Notify Slack on Release

on:
  release:
    types:
      - published

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Installing Dependencies
        run: yarn install --immutable

      - name: Send Slack Notification
        run: yarn run release:send-notification
        env:
          SLACK_PRERELEASE_WEBHOOK_URL: ${{ secrets.SLACK_PRERELEASE_WEBHOOK_URL }}
          SLACK_RELEASE_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_WEBHOOK_URL }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
